<option value="BCHM">Biochemistry</option>
<option value="BIOL">Biology</option>
<option value="BIOS">Biostatistics</option>
<option value="BSBA">Business Administration</option>
<option value="BUJO">Business Journalis</option>
<option value="CHEM">Chemistry</option>
<option value="COMM">Communication Studies</option>
<option value="CS">Computer Science</option>
<option value="ECON">Economics</option>
<option value="EE">Electronic Engineering</option>
<option value="NUTR">Health Nutrition</option>
<option value="MDS">Mathematical Decision Science</option>
<option value="MATH">Mathematics</option>
<option value="OR">Operations Research</option>
<option value="PHIL">Philosophy</option>
<option value="PHYS">Physics</option>
<option value="PSYC">Psychology</option>
<option value="STAT">Statistics</option>
